doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      auth_token_value: HoneyCal\Shared\Infrastructure\Persistence\Doctrine\AuthTokenValueType
      uuid: HoneyCal\Shared\Infrastructure\Persistence\Doctrine\UuidType
      created_at: HoneyCal\Shared\Infrastructure\Persistence\Doctrine\CreatedAtType
      updated_at: HoneyCal\Shared\Infrastructure\Persistence\Doctrine\UpdatedAtType
      email: HoneyCal\Shared\Infrastructure\Persistence\Doctrine\EmailType
      user_id: HoneyCal\Shared\Infrastructure\Persistence\Doctrine\UserIdType
      action_id: HoneyCal\Habits\Infrastructure\Persistence\Doctrine\ActionIdType
      next_occurrence: HoneyCal\Habits\Infrastructure\Persistence\Doctrine\ValueObjects\Action\NextOccurrenceType
      recurrence: HoneyCal\Habits\Infrastructure\Persistence\Doctrine\RecurrenceType
      auth_user_id: HoneyCal\Auth\Infrastructure\Persistence\Doctrine\AuthUserIdType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'

    profiling_collect_backtrace: "%kernel.debug%"
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
    mappings:
      AuthUser:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/HoneyCal/Auth/Infrastructure/Persistence/Doctrine/"
        prefix: 'HoneyCal\Auth\Domain'
      AuthToken:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/HoneyCal/Auth/Infrastructure/Persistence/Doctrine/"
        prefix: 'HoneyCal\Auth\Domain'
      Action:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/HoneyCal/Habits/Infrastructure/Persistence/Doctrine/"
        prefix: 'HoneyCal\Habits\Domain'

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
