security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    auth_users:
      id: HoneyCal\Auth\Infrastructure\Security\AuthProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      access_token:
        provider: auth_users
        token_handler: HoneyCal\Auth\Infrastructure\Security\AccessTokenHandler

    login:
      pattern: ^/api/auth
      stateless: true
      provider: auth_users
      json_login:
        check_path: /api/auth
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern:   ^/api
      stateless: true
      provider: auth_users
      jwt: ~

  access_control:
    - { path: ^/api/auth, roles: PUBLIC_ACCESS }
    - { path: ^/api,       roles: PUBLIC_ACCESS }

when@test:
  security:
      password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
          algorithm: auto
          cost: 4
          time_cost: 3
          memory_cost: 10
