controllers:
  resource:
    path: ../src/App/Controller/
    namespace: App\Controller
  type: attribute

actions.get:
  methods: GET
  path: /api/actions
  controller: App\Controller\ActionsGetController

actions.post:
  methods: POST
  path: /api/actions
  controller: App\Controller\ActionsPostController
