scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "php_backend"
    scrape_interval: 5s
    static_configs:
      - targets: ["app-php:8040"]
